/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ooadassignment2;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static ooadassignment2.OoadAssignment2.obj;

/**
 *
 * @author Salva
 */
public class UpdateMarks extends javax.swing.JFrame {

    String course="";
    String section="";
    String student="";
    float marks=0;
    String descrip="";
    String teacher="";
    /**
     * Creates new form UpdateMarks
     */
    public UpdateMarks(String tid) throws SQLException {
       
        initComponents();
        if(tid=="")
            tid="1";
        teacher=tid;
        ResultSet rs=obj.getCourse(tid);
        while(rs.next())
        {
            String t=rs.getString("cname");
            
         jComboBox1.addItem(t);
         
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Coursewala = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        sectionwala = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        descriptionwala = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        studentwala = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        insertwala = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        updatewala = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Course");

        Coursewala.setText("Select");
        Coursewala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoursewalaActionPerformed(evt);
            }
        });

        jLabel2.setText("Section");

        sectionwala.setText("Select");
        sectionwala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionwalaActionPerformed(evt);
            }
        });

        jLabel4.setText("Description");

        descriptionwala.setText("Select");
        descriptionwala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionwalaActionPerformed(evt);
            }
        });

        jLabel5.setText("Student");

        studentwala.setText("Select");
        studentwala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentwalaActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel3.setText("Marks");

        insertwala.setText("Insert");
        insertwala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertwalaActionPerformed(evt);
            }
        });

        updatewala.setText("Update");

        jLabel6.setText("Total");

        jLabel7.setText("Weightage");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(22, 22, 22)
                            .addComponent(descriptionwala))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(22, 22, 22)
                            .addComponent(studentwala))
                        .addComponent(sectionwala)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Coursewala)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(jTextField2))))
                        .addGap(28, 28, 28)
                        .addComponent(insertwala)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updatewala, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Coursewala)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sectionwala)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentwala)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionwala)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertwala)
                    .addComponent(updatewala))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CoursewalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoursewalaActionPerformed
        // TODO add your handling code here:
        String courseSelected=jComboBox1.getSelectedItem().toString();
        
        try {
            course=obj.CidbyCname(courseSelected);
        } catch (SQLException ex) {
            Logger.getLogger(UpdateMarks.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ResultSet rs= obj.getSections(teacher, courseSelected);
            while (rs.next())
            {
                String t=rs.getString("secid").toString();
                jComboBox2.addItem(t);
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateMarks.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_CoursewalaActionPerformed

    private void sectionwalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionwalaActionPerformed
        // TODO add your handling code here:
        String sectionSelected=jComboBox2.getSelectedItem().toString();
        section=sectionSelected;
        try 
        {
            ResultSet rs= obj.getStudents(section, course);
            while (rs.next())
            {
                jComboBox3.addItem(rs.getString("stid"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateMarks.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sectionwalaActionPerformed

    private void descriptionwalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionwalaActionPerformed
        // TODO add your handling code here:
        
        descrip=jComboBox4.getSelectedItem().toString();
    }//GEN-LAST:event_descriptionwalaActionPerformed

    private void studentwalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentwalaActionPerformed
        // TODO add your handling code here:
        student=jComboBox3.getSelectedItem().toString();
        jComboBox4.addItem("Assignment 1");
        jComboBox4.addItem("Assignment 2");
        jComboBox4.addItem("Assignment 3");
        jComboBox4.addItem("Quiz 1");
        jComboBox4.addItem("Quiz 2");
        jComboBox4.addItem("Quiz 3");
        jComboBox4.addItem("Mid 1");
        jComboBox4.addItem("Mid 2");
        jComboBox4.addItem("Final");
    }//GEN-LAST:event_studentwalaActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void insertwalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertwalaActionPerformed
        // TODO add your handling code here:
        if(course!="" && section!="" && student!="" && descrip!="" && jTextField1.getText()!="" && jTextField2.getText()!="" && jTextField3.getText()!=""  )
        {
            String m=jTextField1.getText().toString();
            marks=Float.valueOf(m);
            
            String t=jTextField2.getText().toString();
            float total=Float.parseFloat(t);
            
            String w=jTextField3.getText().toString();
            float weigh=Float.parseFloat(w);
            
            int x=0;
            try {
                x = obj.setMarks(course, student, descrip,marks,section,total,weigh);
            } catch (SQLException ex) {
                Logger.getLogger(UpdateMarks.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            if(x>0)
                JOptionPane.showMessageDialog(rootPane, "Marks Uploaded", "Done", HEIGHT);
            else
                JOptionPane.showMessageDialog(rootPane, "Marks not Uploaded", "Error", HEIGHT);
        }
        else
             JOptionPane.showMessageDialog(rootPane, "Select above options first", "Error", HEIGHT);
    }//GEN-LAST:event_insertwalaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Coursewala;
    private javax.swing.JButton descriptionwala;
    private javax.swing.JButton insertwala;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton sectionwala;
    private javax.swing.JButton studentwala;
    private javax.swing.JButton updatewala;
    // End of variables declaration//GEN-END:variables
}
